<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>go-to-folder-modal-btn</name>
   <tag></tag>
   <elementGuidId>0e548215-78a3-46ff-b95f-ce01639a568d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'go-to-folder-modal-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3142b078-d1e8-4310-92f0-5fd7cd87692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-folder-modal-btn</value>
      <webElementGuid>3578f934-566e-495a-ab05-5a585480eec7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
