<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeleteFolder2</name>
   <tag></tag>
   <elementGuidId>bf2a13d9-4827-47c7-8a40-765aa0aa628a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@id='Delete'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@id='Delete'])[2]</value>
      <webElementGuid>4f908773-ca43-4fd1-aa98-d0e6c9e8e51c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
