<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gotofolderbutton</name>
   <tag></tag>
   <elementGuidId>a2f28911-187e-4fee-8d3f-53c074cbc1fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'go-to-folder-modal-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c18d09e-da63-41bd-aba5-49cee0d1639c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-folder-modal-btn</value>
      <webElementGuid>d8ab91d6-548f-4883-99fd-39d5446fbd4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
