<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pagination-dropdown</name>
   <tag></tag>
   <elementGuidId>3aa02611-36be-41d3-b661-10618e86fa09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'pagination-dropdown-auditlogs_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c88363e5-1be4-4ea7-aae0-4b55504a85de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pagination-dropdown-auditlogs_input</value>
      <webElementGuid>02a5a53b-d9ed-449c-84c9-3f46fa5c85bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
